import React, { useState } from 'react';
import AnalysisSection from './components/AnalysisSection';
import AppTable from './components/AppTable';

function App() {
  const [activeTab, setActiveTab] = useState('analysis');

  return (
    <div className="container">
      {/* Hero Section */}
      <header style={{ textAlign: 'center', marginBottom: '3rem', paddingTop: '2rem' }}>
        <div style={{
          display: 'inline-block',
          padding: '0.5rem 1rem',
          background: 'rgba(99, 102, 241, 0.1)',
          color: '#818cf8',
          borderRadius: '999px',
          fontSize: '0.85rem',
          marginBottom: '1rem',
          fontWeight: '500'
        }}>
          Shopify Market Intelligence
        </div>
        <h1 style={{ fontSize: '3.5rem', marginBottom: '1rem', lineHeight: 1.1 }}>
          Top <span className="text-gradient">App Trends</span> 2025
        </h1>
        <p style={{ color: 'var(--text-secondary)', maxWidth: '600px', margin: '0 auto', fontSize: '1.1rem' }}>
          Real-time analysis of the fastest growing Shopify Apps launched in the last 6 months.
          Based on 2,600+ crawled data points.
        </p>
      </header>

      {/* Tabs */}
      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '3rem' }}>
        <div className="glass-panel" style={{ padding: '0.5rem', display: 'flex', gap: '0.5rem', borderRadius: '12px' }}>
          <button
            className={`btn ${activeTab === 'analysis' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setActiveTab('analysis')}
          >
            📊 Market Analysis
          </button>
          <button
            className={`btn ${activeTab === 'data' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setActiveTab('data')}
          >
            💾 Raw Data Explorer
          </button>
        </div>
      </div>

      {/* Content */}
      <main>
        {activeTab === 'analysis' ? <AnalysisSection /> : <AppTable />}
      </main>

      <footer style={{ marginTop: '5rem', textAlign: 'center', color: 'var(--text-secondary)', paddingBottom: '2rem' }}>
        <p>Generated by Antigravity Agent &bull; 2025</p>
      </footer>
    </div>
  );
}

export default App;
